### ISSUE TITLE
ADMINER_PLUGINS not working

### ISSUE THREAD

**Issue by Denitz** [shyim/adminerevo-docker#1]
```
        environment:
            ADMINER_PLUGINS: tables-filter enum-option
```

See error in container log:
`2024-05-02 11:07:06 /entrypoint.sh: line 14: can't create plugins-enabled/001-tables-filter.php: nonexistent directory`

**Comment by shyim** [comment]
is fixed and the image has been updated :)

**Comment by Denitz** [comment]
Sorry, but I still see
`2024-05-13 08:00:29 /entrypoint.sh: line 16: can't create /var/www/html/plugins-enabled/001-tables-filter.php: Permission denied`

**Comment by shyim** [comment]
can you post the full compose description?

**Comment by Denitz** [comment]
Please see below. Note that I have custom plugins mapped, but even if I remove them, I still get the same error.
Ubuntu 22 via WSL2 for Win11.
```
    adminer:
        container_name: adminer
        image: shyim/adminerevo:latest
        restart: unless-stopped
        networks:
            - app
        environment:
            # Native plugins list
            ADMINER_PLUGINS: tables-filter enum-option
        volumes:
            - ./config/adminer/plugins-enabled/login-servers.php:/var/www/html/plugins-enabled/login-servers.php
            - ./config/adminer/plugins-enabled/myScroll.php:/var/www/html/plugins-enabled/myScroll.php
            - ./config/adminer/plugins-enabled/stickyColumns.php:/var/www/html/plugins-enabled/stickyColumns.php

            - ./config/adminer/adminer.css:/var/www/html/adminer.css
```
