### ISSUE TITLE
ADMINER_DEFAULT_SERVER not working

### ISSUE THREAD

**Issue by evnix** [shyim/adminerevo-docker#2]
```
ubuntu@testluna2:~$ cat  /data/services/adminer.yml 
version: "3"
services:
  adminer:
    image: ghcr.io/shyim/adminerevo:latest
    user: nonroot
    working_dir: /tmp
    volumes: []
    environment:
    - ADMINER_DEFAULT_SERVER=host.docker.internal
    container_name: ghcr-io-shyim-adminerevo-latest_cntnr
    command: ""
    ports:
    - 9191:8080
    extra_hosts:
    - host.docker.internal:host-gateway
volumes: {}
ubuntu@testluna2:~$ docker exec -it 63df550d116f /bin/sh
/tmp $ 
/tmp $ ls
sess_2j11ajt3sp0j10qd8i9eih3t28  sess_e9c7v32c3ip6c3s3nrdkdeno2m
/tmp $ ls /
bin            entrypoint.sh  home           lib64          proc           run            sys            usr
dev            etc            lib            opt            root           sbin           tmp            var
/tmp $ echo $ADMINER_DEFAULT_SERVER
host.docker.internal
/tmp $ 
```
but it still shows 'db' as default

![image](https://github.com/shyim/adminerevo-docker/assets/1516273/34276aca-216b-48e5-9fb5-a9a33dbd213a)

**Comment by Kofl** [comment]
Can confirm the issue, unfortunately not working:

```
version: '3'
services:
  adminer:
    image: ghcr.io/shyim/adminerevo:latest
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: mariadb10.domain.com
    ports:
      - 8088:8080

```
